### ISSUE TITLE
Too Many Connections with cron job/queue

### ISSUE THREAD

**Issue by riconeitzel** [oroinc/crm#299]
Running orocrm with the supervisord and cronjobs results in an increasing number of open but unused mysql connections.

<img width="1138" alt="screen shot 2018-02-06 at 10 49 45" src="https://user-images.githubusercontent.com/930706/35852547-7b068934-0b2b-11e8-9d3a-c5eae923c4da.png">

I can't find a way to see if these are just abandoned non-persistent connections or if oro is using persistent connections without closing them properly.

```
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: orocrm
    database_user: orocrm
    database_password: xxxx
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: null
    mailer_encryption: null
    mailer_user: null
    mailer_password: null
    websocket_bind_address: 0.0.0.0
    websocket_bind_port: 8080
    websocket_frontend_host: '*'
    websocket_frontend_port: 8080
    websocket_backend_host: '*'
    websocket_backend_port: 8080
    websocket_frontend_path: ''
    websocket_backend_path: ''
    web_backend_prefix: ''
    session_handler: session.handler.native_file
    locale: de_DE
    secret: xxxx
    installed: '2017-12-04T13:53:32+00:00'
    assets_version: 058df845
    assets_version_strategy: time_hash
    message_queue_transport: dbal
    message_queue_transport_config: null
```

Current Version: 2.6 (9e2a60609f8e31b2b75c8de39ab2cb4ab2b40f9e)
