### ISSUE TITLE
Problem Overriding Oro Forms.

### ISSUE THREAD

**Issue by Briones** [oroinc/crm#313]
I had the previous 2.3 version of OroCRM and I'm trying to upgrade to 3.0, I realize that the form overriding doesn't work in the same way that in the previous version, and I was able to locate the problem after some days of work:

In this commit:
https://github.com/oroinc/crm/commit/aeea97b8f2e39cb327b68e95d8908c9180e6b0eb#diff-f621e811542f8bb452c45fcfe8c0acc4R18

Do you change the aliases for FQCN but you also hardcode the FQCN for Oro Forms, so there is no way to override it just overriding the form type classs parameter, for example before we used to just do this to override a form:

`oro_account.type.account.class: Company\CRM\Bundle\AccountBundle\Form\Type\AccountType`

But now that is not enought, because you hardcoded the value of the Oro Form in the Factory:

```yml
  oro_account.form.account:
        class:                                      Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments: ["oro_account_form", Oro\Bundle\AccountBundle\Form\Type\AccountType, null]
```

I think that should be:

```yml
  oro_account.form.account:
        class:                                      Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments: ["oro_account_form", "%oro_account.type.account.class%", null]
```

In order to use the Oro form in normal scenarios and the overrided form when the class is overrided. This problem is with all forms that have fixed the Oro FQCN.

The workaround for this issue right now is overriding also the oro_account.form.account with the parameter `oro_account.type.account.class` instead of the fixed `Oro\Bundle\AccountBundle\Form\Type\AccountType`, but I think it shouldn't be that way.
