### ISSUE TITLE
Override native JS file

### ISSUE THREAD

**Issue by simoncarre** [oroinc/crm#367]
Hello,

I would like to override a javascript file in my OroCRM project (file `vendor/oro/platform/src/Oro/Bundle/FilterBundle/Resources/public/js/filter/date-filter.js`).
What is the proper way to make this change?

I tried this modification in the `jsmodules.yml` file of my custom bundle but without success:

```
map:
    '*':
        'oro/filter/date-filter': 'acme/filter/date-filter'
aliases:
    acme/filter/date-filter$: bundles/acme/js/filter/date-filter
```

I have the following error in the console when I try to access the filters of my widget on the dashboard:
![capture_001](https://user-images.githubusercontent.com/1229419/152039034-6fce071d-fec8-4f6a-9f7a-373283d4c67d.png)

**Comment by Grygir** [comment]
Hello,

Try following configuration:
```yaml
aliases:
    acme/filter/date-filter$: acme/js/filter/date-filter # no `bundles` part
map:
    "*":
        oro/filter/date-filter: acme/filter/date-filter
    # to get access to original `oro/filter/date-filter` from `acme/filter/date-filter`
    acme/filter/date-filter:
        oro/filter/date-filter: oro/filter/date-filter 
```

```js
define(function(require) {
   const DateFilter = require('oro/filter/date-filter');

   const AcmeDateFilter = DateFilter.extend({
      constructor: function AcmeDateFilter(options) {
         AcmeDateFilter.__super__.constructor.call(this, options);
      },

      // ...
   });

   console.log("It's 'acme/filter/date-filter'", AcmeDateFilter,", that extends 'oro/filter/date-filter'", DateFilter);

   return AcmeDateFilter;
});

```
![Screenshot 2022-02-03 at 11 54 24](https://user-images.githubusercontent.com/131182/152320049-8414429a-569d-46c7-ac33-4443de4f1bde.png)
